---
- name: Build App Container
  gather_facts: false
  hosts: immfly-debian10

  tasks:
    - name: Copy app directory
      copy:
        src: /docker/clock_app
        dest: /tmp/web-project/
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'

    - name: Build container image for app backend
      docker_image:
        name: clock-app
        tag: v1.0
        build:
          path: /tmp/web-project/clock_app
        state: present
        source: build
