---
- name: Clean old debian repos
  gather_facts: false
  hosts: immfly-debian10

  tasks:
    - name: Add global debian repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian buster main contrib non-free
        state: present
        update_cache: false
    - ansible.builtin.apt_repository:
        repo: deb-src http://deb.debian.org/debian buster main contrib non-free
        state: present
        update_cache: false
    - ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian buster-updates main contrib non-free
        state: present
        update_cache: false
    - ansible.builtin.apt_repository:
        repo: deb-src http://deb.debian.org/debian buster-updates main contrib non-free
        state: present
        update_cache: false

    - name: Delete old ftp.caliu.cat
      ansible.builtin.apt_repository:
        repo: deb http://ftp.caliu.cat/debian/ buster main non-free contrib
        state: absent
        update_cache: false
    - ansible.builtin.apt_repository:
        repo: deb-src http://ftp.caliu.cat/debian/ buster main non-free contrib
        state: absent
        update_cache: false
    - ansible.builtin.apt_repository:
        repo: deb http://ftp.caliu.cat/debian/ buster-updates main contrib non-free
        state: absent
        update_cache: false
    - ansible.builtin.apt_repository:
        repo: deb-src http://ftp.caliu.cat/debian/ buster-updates main contrib non-free
        state: absent
